export const productList=[
    { id: 1, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 2, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 3, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 4, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 5, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 6, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 7, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 8, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 9, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 10, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 11, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 12, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 13, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
    { id: 14, name: 'Araimo Power Bank', avatar:"/img/avatar.jpg", stock: 123,status:"active", price:"$140,000" },
  ];