export const userList=[
    { id: 1, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 2, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 3, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 4, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 5, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 6, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 7, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 8, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 9, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 10, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 11, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 12, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 13, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
    { id: 14, userName: 'Adewale James', avatar:"/img/avatar.jpg", email: "adewalejames@gmail.com",status:"active", transaction:"$140,000" },
  ];